#!/bin/bash

set -e
set -x

flavor=$1
platform=$2

tar=`which gtar || true`
if [ ! -x "$tar" ]
then
  tar=`which tar`
  if [ ! -x "$tar" ]
  then
    echo "Could not find usable tar" >/dev/stderr
    exit 1
  fi
fi

usage() {
  echo "usage: $0 [IU | IC] [solaris | debian]" >/dev/stderr
  exit 1
}

fetch_latest() {
  if [ "$IDEA_URL" = "" ]
  then
    IDEA_URL="http://confluence.jetbrains.net/display/IDEADEV/Maia+EAP"
  fi

  echo "Downloading and parsing.. $IDEA_URL"
  read url filename version < <(wget -O - -q $IDEA_URL | LC_ALL=C sed -n -e "/.*\"\(http:\/\/.*\/idea$flavor-.*tar.gz\)\".*/ {
    s,.*\"\(http:\/\/.*\/idea$flavor-.*tar.gz\)\".*,\1,p
    s,.*\(ideaI.-[0-9]*.[0-9]*.tar.gz\).*,\1,p
    s,.*-\([0-9]*.[0-9]*\).tar.gz,\1,p
  }" | xargs)

  echo "Downloading latest version: $version"

  mkdir -p download

  # It would be possible to use the MD5 sum as a check here, then there would be no need to every force a download
  #if [ -r "download/$filename" ]
  #then
  #  echo "$filename is already downloaded"
  #else
  #  echo "Downloading $url..."
  #  wget -O "download/$filename" $url
  #fi

  wget -q -P download -N $url
}

build_common() {
  rm -rf root
  mkdir -p root/usr/share/jetbrains/intellij-idea
  mkdir -p root/usr/bin

  $tar --strip-components 1 -C root/usr/share/jetbrains/intellij-idea -zxf download/$filename

  cp idea.in root/usr/bin/idea
  chmod +x root/usr/bin/idea

  mkdir -p root/usr/share/applications
  cp intellij-idea.desktop root/usr/share/applications/intellij-idea.desktop
}

build_solaris() {
  build_common 

  rm -rf solaris
  mkdir -p solaris

  cp root/usr/share/jetbrains/intellij-idea/bin/idea.vmoptions solaris/
  cat solaris/idea.vmoptions | grep -v yjpagent > root/usr/share/jetbrains/intellij-idea/bin/idea.vmoptions

  sed -e "s,@VERSION@,$version," pkginfo.in > solaris/pkginfo
  cp prototype.in solaris/prototype
  pkgproto root=/ | awk '
   {$5="root"}
   $3 ~ /^\/$/ {$5="?"; $6="?"} 
   $3 ~ /^\/usr$/ {$5="?"; $6="?"}
   $3 ~ /^\/usr\/bin$/ {$5="?"; $6="?"}
   $3 ~ /^\/usr\/share$/ {$5="?"; $6="?"}
   $3 ~ /^\/usr\/share\/applications$/ {$5="?"; $6="?"}
   {printf $1 " " $2 " " $3 " " $4 " " $5 " " $6 " \n"}' >> solaris/prototype
  pkgmk -o -d solaris -f solaris/prototype -r .
  echo "The package was successfully build in solaris/"
  echo "To install run: pfexec pkgadd -d solaris intellij-idea"
}

build_debian() {
  build_common
  mkdir -p root/DEBIAN

  if [ $flavor = "IC" ]
  then
    OTHER_FLAVOR_LOWER=iu
    OTHER_FLAVOR=IU
    FLAVOR_LOWER=ic
  else
    OTHER_FLAVOR_LOWER=ic
    OTHER_FLAVOR=IC
    FLAVOR_LOWER=iu
  fi

  sed \
    -e "s,OTHER_FLAVOR_LOWER,$OTHER_FLAVOR_LOWER," \
    -e "s,OTHER_FLAVOR,$OTHER_FLAVOR," \
    -e "s,FLAVOR_LOWER,$FLAVOR_LOWER," \
    -e "s,FLAVOR,$flavor," \
    -e "s,VERSION,$version," \
    control.in > root/DEBIAN/control

  touch fakeroot.save
  FAKEROOT="fakeroot -i fakeroot.save -s fakeroot.save"
  $FAKEROOT -- chown -R root:root root/
  $FAKEROOT -- dpkg-deb -b root intellij-idea-$FLAVOR_LOWER-$version.deb
}

if [ "$flavor" != "IU" -a "$flavor" != "IC" ]
then
  usage
fi

if [ "$platform" != "solaris" -a "$platform" != "debian" ]
then
  usage
fi

fetch_latest

case "$platform" in
  solaris)
    build_solaris;;
  debian)
    build_debian;;
esac

